name: springcrate
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  fl_chart: ^0.67.0
  flutter_svg: ^2.0.10+1
  multi_select_flutter: ^4.1.3
  firebase_core: ^2.30.1
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  equatable: ^2.0.5
  firebase_auth: ^4.19.4
  flutter_dotenv: ^5.1.0

  user_repository:
    path: packages/user_repository

  services_repository:
    path: packages/services_repository

  transactions_repository:
    path: packages/transactions_repository

  employees_repository:
    path: packages/employees_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Bold.ttf
  assets:
    - lib/assets/
    - .env
